name: gql_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ferry:
  ferry_flutter:
  ferry_hive_store:
  gql_link:
  gql_http_link:
  hive:
  hive_flutter:
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  ferry_generator:
  build_runner:

flutter:

  uses-material-design: true